# Generated by Django 4.2 on 2023-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('hood-001', 'hood-001'), ('hood-002', 'hood-001'), ('hood-003', 'hood-003'), ('jean-001', 'jean-001'), ('sock-001', 'sock-001'), ('head-001', 'head-001')], max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
            ],
        ),
    ]
