# Generated by Django 4.2 on 2023-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(choices=[('hood-001', 'hood-001'), ('hood-002', 'hood-002'), ('hood-003', 'hood-003'), ('jean-001', 'jean-001'), ('sock-001', 'sock-001'), ('head-001', 'head-001')], max_length=8),
        ),
    ]
