# Generated by Django 4.2 on 2023-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_product_stock_quantity_inbound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='receiverd_at',
            new_name='received_at',
        ),
    ]
