# Generated by Django 4.2 on 2023-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_inbound_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
